name: Publish Gem

on:
  push:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.3'
        bundler-cache: true
    - uses: fac/ruby-gem-setup-credentials-action@v2
      with:
        user: ""
        key: rubygems
        token: ${{ secrets.RUBYGEMS_API_KEY }}
    - run: gem build busser-serverspec_chefdk30 --output=latest-release.gem
    - run: gem push --key=rubygems latest-release.gem
