name: Test Gem

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.3'
      - name: Build and test with Rake
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install
          rake
